ARMmbed/mbed-os-example-nfc

NFC_SmartPoster/main.cpp
Traces mess up with timing requested by the PN512 controller.
=> Smart poster: remove traces in callbacks.

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.11.3 .
=> Updating mbed-os to mbed-os-5.11.3

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.11.5 .
=> Updating mbed-os to mbed-os-5.11.5

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.12.0-rc2 .
=> Updating mbed-os to mbed-os-5.12.0-rc2

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.12.0-rc3 .
=> Updating mbed-os to mbed-os-5.12.0-rc3

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.12.0-rc4 .
=> Updating mbed-os to mbed-os-5.12.0-rc4

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.13.0-rc2 .
=> Updating mbed-os to mbed-os-5.13.0-rc2

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag the corresponding 
release branch with mbed-os-5.13.0 .
=> Updating mbed-os to mbed-os-5.13.0

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.13.3 .
=> Updating mbed-os to mbed-os-5.13.3

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
Once you get notification of the release being made public then tag the corresponding 
release branch with mbed-os-5.15.0-rc2 .
=> Updating mbed-os to mbed-os-5.15.0-rc2

NFC_EEPROM/source/main.cpp
This PR https://github.com/ARMmbed/mbed-os/pull/12581 failed due to removing some header files that could affect this.
Failures are
```
Compile [ 99.1%]: main.cpp
[Error] main.cpp@52,13: use of undeclared identifier 'printf'
[Error] main.cpp@64,13: use of undeclared identifier 'printf'
[Error] main.cpp@66,13: use of undeclared identifier 'printf'
[Error] main.cpp@74,13: use of undeclared identifier 'printf'
[Error] main.cpp@76,13: use of undeclared identifier 'printf'
[Error] main.cpp@81,9: use of undeclared identifier 'printf'
[Error] main.cpp@85,9: use of undeclared identifier 'printf'
```
=> main: fix printf  include

NFC_SmartPoster/main.cpp
Fixes https://github.com/ARMmbed/mbed-os-example-nfc/issues/63
=> NFC_SmartPoster: Stop execution if initialization fails

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.1.0 release of mbed-os.
=> Update for mbed-os-6.1.0

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.2.0 release of mbed-os.
=> Update for mbed-os-6.2.0

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-5.15.5 release of mbed-os.
=> Update for mbed-os-5.15.5

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.2.1 release of mbed-os.
=> Update for mbed-os-6.2.1

NFC_EEPROM/CMakeLists.txt
This was missing from the previous commit.
The application needs to be aware of the configuration module in order to use the target labels to add subdirectory to build EEPROM drivers.
Reviewers
@0xc0170
=> CMake: Fix missing configuration module

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.3.0 release of mbed-os.
=> Update for mbed-os-6.3.0

NFC_SmartPoster/CMakeLists.txt, NFC_SmartPoster/mbed_app.json
Mbed OS has multiple targets that can be linked to as required.
Reviewers: @0xc0170 @rajkan01
=> CMake: Add required Mbed OS component

NFC_EEPROM/source/target/CMakeLists.txt
- The directory starts with special prefixes `TARGET_`  gets added into the build based on target configuration instead of calling utility function mbed_add_cmake_directory_if_labels().
@hugueskamba
=> CMake: replace usage of the mbed_add_cmake_directory_if_labels() func

NFC_EEPROM/CMakeLists.txt, NFC_SmartPoster/CMakeLists.txt
They are now prefixed with "mbed-" instead of "mbed-os-"
Reviewers
@rajkan01 @0xc0170
=> CMake: Use renamed Mbed CMake targets component

NFC_EEPROM/CMakeLists.txt, NFC_SmartPoster/CMakeLists.txt
- Updated CMakeLists.txt file to call mbed_set_post_build API for setting post-build operations
@0xc0170 @hugueskamba
=> CMake: Call mbed_set_post_build API for setting post build operations

NFC_EEPROM/CMakeLists.txt, NFC_EEPROM/source/target/CMakeLists.txt, NFC_EEPROM/source/target/TARGET_M24SR/CMakeLists.txt, NFC_EEPROM/source/target/TARGET_PN512/CMakeLists.txt, NFC_SmartPoster/CMakeLists.txt, NFC_SmartPoster/mbed_app.json
The CMake support is still in development. For more information, see mbed-os/cmake/README.md
Following ARMmbed/mbed-os#13566
=> Add CMakelists

NFC_EEPROM/EEPROMDriver/target/TARGET_M24SR/CMakeLists.txt, NFC_EEPROM/EEPROMDriver/target/TARGET_M24SR/eeprom_driver.lib
Mbed OS now provides the driver thus remove lib file
to download it from another external repository.
Preceding PR: https://github.com/ARMmbed/mbed-os/pull/14092
=> M24SR: Use driver from Mbed OS repository

NFC_EEPROM/CMakeLists.txt, NFC_SmartPoster/CMakeLists.txt
`mbed_set_mbed_target_linker_script` was removed from mbed-os.
This PR depends on ARMmbed/mbed-os#14199
=> Remove deprecated function from CMakeLists.txt

tests/SmartPoster_noShield.log
Current error message is no longer working. Updating to a generic error message.
=> Generic error message in SmartPoster_noShield.log

NFC_EEPROM/CMakeLists.txt
As we are moving to CMake OBJECT libraries for optional
components, applications can no longer rely on them
to obtain other libraries they themselves need.
Also remove call to mbed_configure_app_target() as it is
no longer required.
Reviewers
@0xc0170
=> CMake: Link with mbed-events as the application requires it

NFC_EEPROM/README.md, NFC_SmartPoster/CMakeLists.txt, NFC_SmartPoster/README.md, README.md
This updates the `README.md` files to add instructions for Mbed CLI 2, as well as clarifying the supported targets for the examples and updating some incorrect paths.
=> docs: Add Mbed CLI 2 instructions to README

NFC_EEPROM/EEPROMDriver/target/TARGET_PN512/EEPROMDriver.cpp, NFC_EEPROM/mbed_app.json, NFC_SmartPoster/mbed_app.json
This PR updates this example to use the new Arduino pin names (e.g. D0 -> ARDUINO_UNO_D0).
=> Update Arduino pin names

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.12.0 release of mbed-os.
=> Update for mbed-os-6.12.0

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.13.0 release of mbed-os.
=> Update for mbed-os-6.13.0

NFC_EEPROM/CMakeLists.txt, NFC_SmartPoster/CMakeLists.txt
So CMake can work correctly we need to define our project before we add
dependencies, otherwise the project we depend on will be registered as
the current project.
=> CMake: Make applications the top level CMake projects

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.15.0 release of mbed-os.
=> Update for mbed-os-6.15.0

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.16.0 release of mbed-os.
=> Update for mbed-os-6.16.0

NFC_EEPROM/mbed-os.lib, NFC_SmartPoster/mbed-os.lib
mbed-os-6.17.0 release of mbed-os.
=> Update for mbed-os-6.17.0
